definitions:
  steps:
    - step: &build-lint-test
        name: Build -> Lint -> Test
        image: python:3.8.3
        caches:
          - pip
        script:
          - export FLASK_RUN_PORT=5000
          - export FLASK_ENV=development
          - export STAGE=dev
          - export FLASK_APP=src/app.py
          - export FLASK_DEBUG=True

          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export PROPAGATE_EXCEPTIONS=True

          - export DB_URL=postgresql://user:password@127.0.0.1:5432/my-db-please-update
          - export CLIENT_SECRET_KEY=this-is-client-secret-key
          - export JWT_SECRET_KEY=this-is-jwt-secret-key
          - export JWT_ACCESS_TOKEN_EXPIRES_MINUTES=30
          - export JWT_REFRESH_TOKEN_EXPIRES_DAYS=7

          - pip install pipenv

          - pipenv install --dev

          # Running Lint Analysis
          - pipenv run pre-commit install
          - pipenv run pre-commit run --all-files

          # Running Unit and Integration Tests
          - pipenv run pytest --cov-report xml --cov-report term-missing --junitxml=pytest.xml --cov=src tests -vvs

        artifacts:
          - coverage.xml
          - pytest.xml

    - step: &sonar-scan
        name: SonarScan
        script:
          - echo 'SonarScan will happen here'

    - step: &deploy-dev
        name: Deploy -> dev
        deployment: dev
        script:
          - echo 'This will deploy to dev'

    - step: &deploy-stg
        name: Deploy -> stg
        deployment: stg
        script:
          - echo 'This will deploy to stg'

    - step: &deploy-prod
        name: Deploy -> prod
        trigger: manual
        deployment: prod
        script:
          - echo 'This will deploy to prod'

pipelines:
  default:
    - step: *build-lint-test
    - step: *sonar-scan

  pull-requests:
    "**":
      - step: *build-lint-test

  branches:
    develop:
      - step: *build-lint-test
      - step: *sonar-scan
      - step: *deploy-dev
    master:
      - step: *build-lint-test
      - step: *sonar-scan
      - step: *deploy-stg

  tags:
    v*:
      - step: *build-lint-test
      - step: *sonar-scan
      - step: *deploy-prod
