definitions:
  steps:
    - step: &build-lint-test
        name: Build -> Lint -> Test
        image: python:3.8.3
        caches:
          - pip
        script:
          - export FLASK_RUN_PORT=5000
          - export FLASK_ENV=development
          - export STAGE=dev
          - export FLASK_APP=src/app.py
          - export FLASK_DEBUG=True

          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export PROPAGATE_EXCEPTIONS=True

          - export DB_URL=postgresql://user:password@127.0.0.1:5432/my-db-please-update
          - export CLIENT_SECRET_KEY=this-is-client-secret-key
          - export JWT_SECRET_KEY=this-is-jwt-secret-key
          - export JWT_ACCESS_TOKEN_EXPIRES_MINUTES=30
          - export JWT_REFRESH_TOKEN_EXPIRES_DAYS=7

          - pip install pipenv

          - pipenv install --dev

          # Running Lint Analysis
          - pipenv run pre-commit install
          - pipenv run pre-commit run --all-files

          # Running Unit and Integration Tests
          - pipenv run pytest --cov-report xml --cov-report term-missing --junitxml=pytest.xml --cov=src tests -vvs

        artifacts:
          - coverage.xml
          - pytest.xml

    - step: &sonar-scan
        name: SonarScan
        image: naeemark/sonar-scanner:latest
        script:
          - if [[ 1 == $(cat continue_sonar) ]]; then bitbucket-sonar-scanner; else echo 'Skipped SonarScan'; fi

    - step: &init-deploy-dev
        name: Set Stage
        script:
          - echo dev > stage-prefix
        artifacts:
          - stage-prefix

    - step: &pre-deploy
        name: Pre-Deploy -> Dev
        image: atlassian/default-image:2
        script:
          - export STAGE=$(cat stage-prefix)
          - export DOCKER_IMAGE_NAME=$(echo ${ECR_REPOSITORY_TEMPLATE} | envsubst)
          - export DOCKER_IMAGE_URI=${ECR_URI}/${DOCKER_IMAGE_NAME}

          - echo ${DOCKER_IMAGE_NAME} > docker-image-name
          - echo ${DOCKER_IMAGE_URI} > docker-image-uri
          - echo ${CLUSTER_NAME_TEMPLATE} | envsubst > cluster-name
          - echo ${SERVICE_NAME_TEMPLATE} | envsubst > service-name
          - echo ${TASK_DEFINITION_TEMPLATE} | envsubst > task-definition.json

          # Checks if sonar host is available
          - if [[ $(curl -sL -w "%{http_code}\n" $SONAR_URL -o /dev/null -m 3) == 200 ]]; then echo 1 > continue_sonar; else echo 0 > continue_sonar ; fi
        artifacts:
          - docker-image-name
          - cluster-name
          - service-name
          - task-definition.json
          - continue_sonar

    - step: &build_push_docker_image
        name: Build, Push Docker Image
        services:
          - docker
        caches:
          - docker
        script:
          - export FLASK_RUN_PORT=5000
          - export FLASK_ENV=development
          - export STAGE=dev
          - export FLASK_APP=src/app.py
          - export FLASK_DEBUG=True

          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export SQLALCHEMY_TRACK_MODIFICATIONS=False
          - export PROPAGATE_EXCEPTIONS=True

          - export DB_URL=postgresql://user:password@127.0.0.1:5432/my-db-please-update
          - export CLIENT_SECRET_KEY=this-is-client-secret-key
          - export JWT_SECRET_KEY=this-is-jwt-secret-key

          - export DOCKER_IMAGE_NAME=$(cat docker-image-name)

          - docker build -t ${DOCKER_IMAGE_NAME} .
          - docker inspect ${DOCKER_IMAGE_NAME}

          - pipe: atlassian/aws-ecr-push-image:1.1.2
            variables:
              IMAGE_NAME: ${DOCKER_IMAGE_NAME}
              TAGS: "build-${BITBUCKET_BUILD_NUMBER} ${BITBUCKET_TAG} $(date +%s) latest"
        artifacts:
          - cluster-name
          - service-name
          - task-definition.json

    - step: &deploy-dev
        name: Deploy -> dev
        image: atlassian/default-image:2
        deployment: Development
        script:
          - pipe: atlassian/aws-ecs-deploy:1.1.3
            variables:
              CLUSTER_NAME: $(cat cluster-name)
              SERVICE_NAME: $(cat service-name)
              TASK_DEFINITION: "task-definition.json"

    - step: &test_vars_to_file
        name: Test - Vars > File
        image: atlassian/default-image:2
        script:
          - export STAGE=dev
          - export DOCKER_IMAGE_NAME=$(echo ${ECR_REPOSITORY_TEMPLATE} | envsubst)
          - export DOCKER_IMAGE_URI=${ECR_URI}/${DOCKER_IMAGE_NAME}

          - echo "export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> test-vars-file
          - echo "export DOCKER_IMAGE_URI=${DOCKER_IMAGE_URI}" >> test-vars-file

          # - echo ${CLUSTER_NAME_TEMPLATE} | envsubst >> test-vars-file
          # - echo ${SERVICE_NAME_TEMPLATE} | envsubst >> test-vars-file

          - echo "export CLUSTER_NAME=$(echo ${CLUSTER_NAME_TEMPLATE} | envsubst)" >> test-vars-file
          - echo "export SERVICE_NAME=$(echo ${SERVICE_NAME_TEMPLATE} | envsubst)" >> test-vars-file
          - echo "export TEST_VAR_A=NOTHING" >> test-vars-file
          - echo "export TEST_VAR_B=$STAGE" >> test-vars-file
        artifacts:
          - test-vars-file

    - step: &test_vars_from_file
        name: Test - Vars < File
        image: atlassian/default-image:2
        script:
          - cat test-vars-file
          - while read line; do $line; done < test-vars-file
          - echo $TEST_VAR_B
          - env

pipelines:
  branches:
    x-cicd:
      - step: *build-lint-test
      - step: *init-deploy-dev
      - step: *pre-deploy
      - step: *build_push_docker_image
      - step: *sonar-scan
      - step: *deploy-dev
      # - step: *test_vars_to_file
      # - step: *test_vars_from_file
